server:
  port: 9010
spring:
  application:
    name: tensquare-friend
  datasource:
    url: jdbc:mysql://192.168.216.133:3306/tensquare_friend
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true
jwt:
  config:
    key: itcast
